### ISSUE TITLE
Strange case of "Maximum reruns exceeded for ExecEngine"

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/prototype#95]
This issue was first seen in Ampersand-v4.6.2. I have reproduced the symptoms in [RAP](https://rap.cs.ou.nl) for ease of reproduction. This RAP compiles with Ampersand-v4.3.0, so the bug is present in that version too.

# What happened?
When making a prototype of a script, I installed the application with the following result:
![afbeelding](https://user-images.githubusercontent.com/275768/167626606-36da5c85-e9d2-4e07-a100-491904f0eccd.png)

This is the script:
```Ampersand
CONTEXT Issue
   CLASSIFY Vrijwilliger ISA Persoon

   RELATION personalia[Aanmelding*Persoon] 
   RELATION naam[Aanmelding*Tekst] [UNI]
   RELATION naam[Persoon*Tekst] [UNI]
   ROLE ExecEngine MAINTAINS MaakPersoonOBVAanmelding
   RULE MaakPersoonOBVAanmelding: I[Aanmelding]/\naam;naam~ |- personalia;personalia~
     VIOLATION (TXT "{EX} InsAtom;Vrijwilliger"
               ,TXT "{EX} InsPair;personalia;Aanmelding;",SRC I,TXT ";Persoon;_NEW"
               ,TXT "{EX} InsPair;naam;Persoon;_NEW;Tekst;",SRC naam
             )

   RELATION email[Persoon*EmailAdres] [INJ]
   RELATION email[Aanmelding*EmailAdres] [UNI]
   -- ENFORCE email[Persoon*EmailAdres] >: personalia~;I[Aanmelding];email
   ROLE ExecEngine MAINTAINS MaakPersoonsemail
   RULE MaakPersoonsemail: personalia~;I[Aanmelding];email |- email
   VIOLATION ( TXT "{EX} InsPair;email;Persoon;",SRC I, TXT ";EmailAdres;", TGT I )

   POPULATION email[Aanmelding*EmailAdres] CONTAINS
    [( "1" , "stef.joosten@ou.nl" ), ( "3" , "stef.joosten@ou.nl" )]
   POPULATION naam[Aanmelding*Tekst] CONTAINS
    [( "1" , "Stef" ), ( "3" , "Piet" )]

ENDCONTEXT
```
The log file in RAP only gives a little information:
```
[2022-05-10 11:46:54] EXECENGINE.ERROR: Maximum reruns exceeded. Rules fixed in last run:MaakPersoonsemail) [] {"request_id":"fbbf3ac919","ip":"172.20.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
[2022-05-10 11:46:54] APPLICATION.ERROR: Maximum reruns exceeded for ExecEngine {"Rules fixed in last run":["[object] (Ampersand\\Rule\\Rule: MaakPersoonsemail)"]} {"request_id":"fbbf3ac919","ip":"172.20.0.2","method":"GET","url":"/api/v1/admin/installer?defaultPop=true"}
```
The bug goes away by lifting the restriction of injectivity from `RELATION email[Persoon*EmailAdres]`.

**Comment by stefjoosten** [comment]
Issue AmpersandTarski/Ampersand#1283 may be the same issue as this one, except I articulated that issue much more superficially.

**Comment by Michiel-s** [comment]
Hi @stefjoosten, I understand you confusion here. But keep in mind, within a single transaction, rules need to be able to be violated. Because, how else could we do updates to say relations that are defined UNI,TOT.

The exec-engine runs just before checking invariant rules. So this is within the boundaries within a transaction.

I think we can make it work like you state in your diagnosis; checking the existing value first. I do see 2 issues here:
1. Adds additional query (thus database interaction) for every write. Time penalty might be an issue.
2. Changes the current behavior in a back-wards incompatible way. To be honest, I cannot oversee the implications for current scripts and prototypes in the wild. Many exec-engine rules just do an Inspair, expecting them to succeed even if there is already a value present; just overwrite.

**Comment by stefjoosten** [comment]
Like yourself, I also expect that existing scripts might not work anymore. @sjcjoosten is also afraid this might happen. Nevertheless, this may not be a reason to let a mistake persist in the code. It is a bug, so we should fix it and face whatever consequence this might have...

**Comment by Michiel-s** [comment]
So far I'm not convinced it's a bug. Call it a feature.

Ampersand defines the rules that govern the transaction. As I explained that is guaranteed.

The question is what we consider allowed within the boundaries of a transaction. I consider all rules the same; whether they are multiplicity constraints or any other other rule. Only when trying to commit a transaction we look if the new state complies with the rules. I don't see why you shouldn't be able to violate a multiplicity constraint within a transaction.

But there is a trade-off; as we know, for performance reasons, it is way better to put all UNI and INJ relations in a concept table. So we technically don't have the option to violate UNI or INJ constraints in the prototypes.

The problem you describe is the combination of a) design choice to let a Inspair on UNI or INJ relation overwrite a existing value with b) a user specific exec-engine rule that doesn't take into account this behavior. Why change (a) if we can fix/signal better situation (b).

**Comment by RieksJ** [comment]
As an old-school &-programmer, I object to the statement "There is a fundamental problem with translating an insert as an update, namely that the Ampersand-programmer didn't ask for a delete, but a delete still occurs."

My first objection is that it is illogical. Not asking for a delete that nevertheless occurs is in my opinion insufficient evidence for having "a fundamental problem with translating an insert as an update." And what to think of the fact that programmers also do not ask for a create, but nevertheless, the (php)code of `InsPair` has the statements `$src = new Atom($a, $srcConcept);` (line 61 of file execEngineFunctions.php) and `$tgt = new Atom($b, $tgtConcept);` (line 63), and they are often executed. And what about this idiotic `_NEW` atom, that wasn't part of the population when the rule was evaluated? Or the `_AND` keywords that are allowed, enabling a single instruction to do multiple creates, inserts and deletes? If I were to follow this way of reasoning, this is not only spooky but it seems that the suggested conclusion hardly scratches the surface. 

But I don't follow this way of reasoning. I like to build on what we've done up till now. So leg me jog our memories

Long, long ago, in the beginning of this century, @sjcjoosten brilliantly proposed to distinguish between invariants and process rules by adding the `ROLE` syntax, and we were very excited. As we experimented, we soon got the idea that VIOLATIONS were not to be used as error messages, but as instructions to the actor that played the role. The actor would see what was wrong and how to fix it. I recall a nice demo of this (of the VOG) at Justid. 

This idea was expanded to electronic actors. VIOLATION statements became real automatable working instructions for an electronic actor, called the ExecEngine. We coded a set of basic functions to form the language for such working instructions, and extended that as needed. How cool! The ExecEngine could send emails and SMS messages, do  complex computations such as Warshall, collect postcodes from a remote API, etc. 

From this perspective, I can raise my second objection, which is that I find it silly (rather than spooky) to assume there is a 1-1 correspondence between a database instruction (or a relational algebra operator for that matter) and existing ExecEngine functions. It's simply not what the ExecEngine is all about.

The solution is straightforward: we could add a set of ExecEngine functions that behave as the theory likes them to be. It seems like the practical thing to do. As a side-effect, it provides a means to illustrate the difference between theory and practice, not only in theory, but in practice as well.

**Comment by sjcjoosten** [comment]
@RieksJ Point taken as to your first suggestion. As to your second, I did not mean to suggest that there should be a 1-1 correspondence between exec-engine instructions and database instructions, it just so happens to turn out that way for the proposed semantics of insert and update.

As to your solution, we seem to be on the same page, right? That is: use different ExecEngine statements to distinguish different behaviors, so that the implemented behavior which the &-programmer gets is less likely to be a surprise. In the case that would solve this issue: separate Insert and Update.

**Comment by stefjoosten** [comment]
May I try to refocus the discussion?

The current discussion addresses the behavior of the prototype when it works correctly. However, this issue is about the behavior when the prototype produces error messages. The undesirable case is an infinite loop. That is what Ampersand shows today. The desirable case is a message as though UNI was syntactical sugar for `RULE InjEmail : email;email~ |- I[Person]`. Although this might seem a small issue from an Ampersand-builder/maintainer perspective, an infinite loop is very hard to diagnose for the Ampersand programmer. That is why it took me about 13 working hours and huge frustration to diagnose the bug.

The language specification says that UNI is syntactical sugar for the rule `InjEmail`, while practice shows otherwise. This behavior would not have occurred if the prototype would run on a triple store. So, the underlying implementation shows its face between the cracks of the system. For this reason alone, the error message should match that of the rule `InjEmail` where `RELATION email` is not declared [UNI].

What can we do to improve the error message? (By the way, I'm comfortable with the implicit deletion as is. That is beyond the scope of this issue.)

**Comment by RieksJ** [comment]
When an infinite loop ends (yes!), the tool simply dumps some stuff on the screen that works for me, but not for others. Perhaps it is just a matter of polishing it up a bit, saying something like:
~~~
After [n] runs, the ExecEngine could still not resolve all violations. 
Here is a list of rules that still have violations:
- [rulename1]: (src, tgt), (src, tgt), ...
- [rulename2]: (src, tgt), (src, tgt), ...
~~~

I would say that students should be taught how to deal with infinite loops as they will sooner or later run into them (if they keep using &, that is). And by 'dealing with', I mean interpreting the list of violations and wrecking your brain, focusing on how to rewrite your rules so that it no longer occurs (as opposed to rewriting parts of the tool).

**Comment by Michiel-s** [comment]
I'm a bit lost here, but I'll read the discussion and suggestions above and try to propose a fix for the issue of needing to spent to much time to debug. That shouldn't be the case; not for us as developers nor for students.

**Comment by Michiel-s** [comment]
I like the suggestion by @RieksJ 
> The solution is straightforward: we could add a set of ExecEngine functions that behave as the theory likes them to be. It seems like the practical thing to do. As a side-effect, it provides a means to illustrate the difference between theory and practice, not only in theory, but in practice as well.

Backed by @sjcjoosten:
> As to your solution, we seem to be on the same page, right? That is: use different ExecEngine statements to distinguish different behaviors, so that the implemented behavior which the &-programmer gets is less likely to be a surprise. In the case that would solve this issue: separate Insert and Update.

But then @stefjoosten mentions that this issue is not about the implicit deletion
> What can we do to improve the error message? (By the way, I'm comfortable with the implicit deletion as is. That is beyond the scope of this issue.)

So what can we do about the error message?

@stefjoosten, would the error message that @RieksJ suggested have helped you to diagnose the problem more quickly?

```
After [n] runs, the ExecEngine could still not resolve all violations. 
Here is a list of rules that still have violations:
- [rulename1]: (src, tgt), (src, tgt), ...
- [rulename2]: (src, tgt), (src, tgt), ...
Violation that were fixed in the last run:
- [rulename1]: (src, tgt), (src, tgt), ....
```
